[package]
name = "rust_ctgrind_example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crabgrind = "0.1.10"
aria = "0.1.0"
belt-cipher = "0.0.0"
